/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE accountBaseService PLEASE EDIT ../account.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Account } from '../../domain/cmo_db/account';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Account.service.ts
 */

/*
 * SCHEMA DB Account
 *
	{
		Description: {
			type: 'String',
			required : true
		},
		MaxCredit: {
			type: 'Integer',
			required : true
		},
		Name: {
			type: 'String',
			required : true
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		Lessor: {
			type: Schema.ObjectId,
			ref : "Account"
		},
	}
 *
 */
@Injectable()
export class AccountBaseService {

    contextUrl: string = environment.endpoint + '/account';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * AccountService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Account): Observable<Account> {
        return this.http
            .post<Account>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * AccountService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * AccountService.findByLessor
    *   @description CRUD ACTION findByLessor
    *   @param Objectid key Id of model to search for
    *
    */
    findByLessor(id: string): Observable<Account[]> {
        return this.http
            .get<Account[]>(this.contextUrl + '/findByLessor/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * AccountService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Account> {
        return this.http
            .get<Account>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * AccountService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Account[]> {
        return this.http
            .get<Account[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * AccountService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Account): Observable<Account> {
        return this.http
            .post<Account>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
