/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE organizationBaseService PLEASE EDIT ../organization.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Organization } from '../../domain/cmo_db/organization';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../Organization.service.ts
 */

/*
 * SCHEMA DB Organization
 *
	{
		Active: {
			type: 'Boolean'
		},
		ExternalID: {
			type: 'String',
			required : true
		},
		FormalName: {
			type: 'String'
		},
		Liable: {
			type: 'Boolean'
		},
		SearchName: {
			type: 'String'
		},
		Type: {
			type: 'String',
			enum : ["Client", "Prospect", "ProspectBO"]
		},
		//RELATIONS
		//EXTERNAL RELATIONS
		Country: {
			type: Schema.ObjectId,
			ref : "Organization"
		},
		Lessor: {
			type: Schema.ObjectId,
			ref : "Organization"
		},
		LiableParent: {
			type: Schema.ObjectId,
			ref : "Organization"
		},
		Organization: {
			type: Schema.ObjectId,
			ref : "CreditLine"
		},
		Parent: {
			type: Schema.ObjectId,
			ref : "Organization"
		},
		UtlimateParent: {
			type: Schema.ObjectId,
			ref : "Organization"
		},
	}
 *
 */
@Injectable()
export class OrganizationBaseService {

    contextUrl: string = environment.endpoint + '/organization';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * OrganizationService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Organization): Observable<Organization> {
        return this.http
            .post<Organization>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * OrganizationService.delete
    *   @description CRUD ACTION delete
    *   @param ObjectId id Id
    *
    */
    remove(id: string): Observable<void> {
        return this.http
            .delete<void>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * OrganizationService.findByLessor
    *   @description CRUD ACTION findByLessor
    *   @param Objectid key Id of model to search for
    *
    */
    findByLessor(id: string): Observable<Organization[]> {
        return this.http
            .get<Organization[]>(this.contextUrl + '/findByLessor/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * OrganizationService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Organization> {
        return this.http
            .get<Organization>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * OrganizationService.list
    *   @description CRUD ACTION list
    *
    */
    list(): Observable<Organization[]> {
        return this.http
            .get<Organization[]>(this.contextUrl)
            .pipe(map(data => data));
    }

    /**
    * OrganizationService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Organization): Observable<Organization> {
        return this.http
            .post<Organization>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
