/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE LessorBase PLEASE EDIT ../lessor.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
import { Country } from '../country';
import { Lessor } from '../lessor';

/**
 * This is the model of Lessor object
 *
 */
export class LessorBase {

    constructor() { }

    public _id: string;
    public Genesis: string;
    public Name: string;
    public Number: string;
    public Share: number;
    public Type: string;
    // Relations Country
    public Country: Country | string;
    // Relations OperatingEntity
    public OperatingEntity: Lessor | string;
}
