/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|


 * DO NOT EDIT THIS FILE!!
 *
 *  TO CUSTOMIZE OrganizationBase PLEASE EDIT ../organization.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
import { Country } from '../country';
import { Lessor } from '../lessor';
import { Organization } from '../organization';

/**
 * This is the model of Organization object
 *
 */
export class OrganizationBase {

    constructor() { }

    public _id: string;
    public Active?: Boolean;
    public ExternalID: string;
    public FormalName?: string;
    public Liable?: Boolean;
    public SearchName?: string;
    public Type?: string;
    // Relations Country
    public Country: Country | string;
    // Relations Lessor
    public Lessor: Lessor | string;
    // Relations LiableParent
    public LiableParent: Organization | string;
    // Relations Parent
    public Parent: Organization | string;
    // Relations UtlimateParent
    public UtlimateParent: Organization | string;
}
