package com.cmo.db.cmo_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE CreditLineBase PLEASE EDIT ../CreditLine.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of CreditLine object
 * 
 */

import javax.persistence.GeneratedValue;
import javax.persistence.MappedSuperclass;
import javax.persistence.Id;
import javax.persistence.Column;
import java.util.Date;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.FetchType;
import java.util.stream.Collectors;

import com.cmo.db.cmo_db.entity.CreditLine;
// Import relations
import com.cmo.db.cmo_db.entity.Organization;




@MappedSuperclass
public class CreditLineBase {
	
	@Id
	@GeneratedValue
	private Long _id;
	
	// Attributes
	@Column(nullable=false)
    private Integer CreditLimit;
	@Column(nullable=false)
    private Date EndDate;
	@Column()
    private Integer GroupCreditLimit;
	@Column(nullable=false)
    private Date StartDate;
	@Column(nullable=false)
    private String Type;
	
	// Relations Organization
	@ManyToOne(fetch = FetchType.LAZY)
	private Organization Organization;
	
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public Integer getCreditLimit() {
		return CreditLimit;
	}

	public void setCreditLimit(Integer CreditLimit) {
		this.CreditLimit = CreditLimit;
	}
	public Date getEndDate() {
		return EndDate;
	}

	public void setEndDate(Date EndDate) {
		this.EndDate = EndDate;
	}
	public Integer getGroupCreditLimit() {
		return GroupCreditLimit;
	}

	public void setGroupCreditLimit(Integer GroupCreditLimit) {
		this.GroupCreditLimit = GroupCreditLimit;
	}
	public Date getStartDate() {
		return StartDate;
	}

	public void setStartDate(Date StartDate) {
		this.StartDate = StartDate;
	}
	public String getType() {
		return Type;
	}

	public void setType(String Type) {
		this.Type = Type;
	}
    
	public void setOrganization(String Organization) {
		this.Organization = new Organization(Organization);
	}

	public Organization getOrganization() {
		return Organization;
	}
	

    
}