package com.cmo.db.cmo_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE LessorBase PLEASE EDIT ../Lessor.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Lessor object
 * 
 */

import javax.persistence.GeneratedValue;
import javax.persistence.MappedSuperclass;
import javax.persistence.Id;
import javax.persistence.Column;
import java.util.Date;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.FetchType;
import java.util.stream.Collectors;

import com.cmo.db.cmo_db.entity.Lessor;
// Import relations
import com.cmo.db.cmo_db.entity.Country;

import com.cmo.db.cmo_db.entity.Account;

import com.cmo.db.cmo_db.entity.Organization;

import com.cmo.db.cmo_db.entity.Lessor;







@MappedSuperclass
public class LessorBase {
	
	@Id
	@GeneratedValue
	private Long _id;
	
	// Attributes
	@Column(nullable=false,unique=true)
    private String Genesis;
	@Column(nullable=false)
    private String Name;
	@Column(nullable=false,unique=true)
    private String Number;
	@Column(nullable=false)
    private Integer Share;
	@Column(nullable=false)
    private String Type;
	
	// Relations Country
	@ManyToOne(fetch = FetchType.LAZY)
	private Country Country;
	
	// Relations Account
	@OneToMany(mappedBy="Lessor")
	private List<Account> Lessor_Account = new ArrayList<>();
	
	// Relations Organization
	@OneToMany(mappedBy="Lessor")
	private List<Organization> Lessor_Organization = new ArrayList<>();
	
	// Relations OperatingEntity
	@ManyToOne(fetch = FetchType.LAZY)
	private Lessor OperatingEntity;
	
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public String getGenesis() {
		return Genesis;
	}

	public void setGenesis(String Genesis) {
		this.Genesis = Genesis;
	}
	public String getName() {
		return Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}
	public String getNumber() {
		return Number;
	}

	public void setNumber(String Number) {
		this.Number = Number;
	}
	public Integer getShare() {
		return Share;
	}

	public void setShare(Integer Share) {
		this.Share = Share;
	}
	public String getType() {
		return Type;
	}

	public void setType(String Type) {
		this.Type = Type;
	}
    
	public void setCountry(String Country) {
		this.Country = new Country(Country);
	}

	public Country getCountry() {
		return Country;
	}
	
	// Relations Account
	
	public List<Account> getAccount() {
		return this.Lessor_Account;
	}

	public void addAccount(Account Account) {
		this.Lessor_Account.add(Account);
	}

	public void removeAccount(Account Account) {
		this.Lessor_Account.remove(Account);
	}
	
	// Relations Organization
	
	public List<Organization> getOrganization() {
		return this.Lessor_Organization;
	}

	public void addOrganization(Organization Organization) {
		this.Lessor_Organization.add(Organization);
	}

	public void removeOrganization(Organization Organization) {
		this.Lessor_Organization.remove(Organization);
	}
	
	public void setLessor(String OperatingEntity) {
		this.OperatingEntity = new Lessor(OperatingEntity);
	}

	public Lessor getOperatingEntity() {
		return OperatingEntity;
	}
	

    
}