package com.cmo.db.cmo_db.dtos.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE AccountBaseDto PLEASE EDIT ../AccountDto.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the dto of Account object
 * 
 */

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;


import com.cmo.db.cmo_db.entity.Account;
// Import relations
import com.cmo.db.cmo_db.dtos.infos.LessorInfo;



public class AccountBaseDto {
	
	private Long _id;
	
	// Attributes
    private String Description;
    private Integer MaxCredit;
    private String Name;
	
	// Relations Lessor
	private Long Lessor;
	
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public String getDescription() {
		return Description;
	}

	public void setDescription(String Description) {
		this.Description = Description;
	}
	public Integer getMaxCredit() {
		return MaxCredit;
	}

	public void setMaxCredit(Integer MaxCredit) {
		this.MaxCredit = MaxCredit;
	}
	public String getName() {
		return Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}
    
	public void setLessor(LessorInfo Lessor) {
		this.Lessor = Lessor.get_id();
	}

	public Long getLessor() {
		return Lessor;
	}
	

    
}