package com.cmo.db.cmo_db.dtos.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE LessorBaseDto PLEASE EDIT ../LessorDto.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the dto of Lessor object
 * 
 */

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;


import com.cmo.db.cmo_db.entity.Lessor;
// Import relations
import com.cmo.db.cmo_db.dtos.infos.CountryInfo;

import com.cmo.db.cmo_db.dtos.infos.AccountInfo;

import com.cmo.db.cmo_db.dtos.infos.OrganizationInfo;

import com.cmo.db.cmo_db.dtos.infos.LessorInfo;






public class LessorBaseDto {
	
	private Long _id;
	
	// Attributes
    private String Genesis;
    private String Name;
    private String Number;
    private Integer Share;
    private String Type;
	
	// Relations Country
	private Long Country;
	
	// Relations Account
	private List<Long> Lessor_Account = new ArrayList<>();
	
	// Relations Organization
	private List<Long> Lessor_Organization = new ArrayList<>();
	
	// Relations OperatingEntity
	private Long OperatingEntity;
	
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public String getGenesis() {
		return Genesis;
	}

	public void setGenesis(String Genesis) {
		this.Genesis = Genesis;
	}
	public String getName() {
		return Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}
	public String getNumber() {
		return Number;
	}

	public void setNumber(String Number) {
		this.Number = Number;
	}
	public Integer getShare() {
		return Share;
	}

	public void setShare(Integer Share) {
		this.Share = Share;
	}
	public String getType() {
		return Type;
	}

	public void setType(String Type) {
		this.Type = Type;
	}
    
	public void setCountry(CountryInfo Country) {
		this.Country = Country.get_id();
	}

	public Long getCountry() {
		return Country;
	}
	
	// Relations Account
	
	public List<Long> getLessor_Account() {
		return this.Lessor_Account;
	}

    public void setLessor_Account(List<AccountInfo> list) {
		this.Lessor_Account = list.stream()
				.map(el -> el.get_id())
				.collect(Collectors.toList());
	}

	
	// Relations Organization
	
	public List<Long> getLessor_Organization() {
		return this.Lessor_Organization;
	}

    public void setLessor_Organization(List<OrganizationInfo> list) {
		this.Lessor_Organization = list.stream()
				.map(el -> el.get_id())
				.collect(Collectors.toList());
	}

	
	public void setOperatingEntity(LessorInfo OperatingEntity) {
		this.OperatingEntity = OperatingEntity.get_id();
	}

	public Long getOperatingEntity() {
		return OperatingEntity;
	}
	

    
}