package com.cmo.db.cmo_db.dtos.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE OrganizationBaseDto PLEASE EDIT ../OrganizationDto.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the dto of Organization object
 * 
 */

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;


import com.cmo.db.cmo_db.entity.Organization;
// Import relations
import com.cmo.db.cmo_db.dtos.infos.CountryInfo;

import com.cmo.db.cmo_db.dtos.infos.LessorInfo;

import com.cmo.db.cmo_db.dtos.infos.OrganizationInfo;

import com.cmo.db.cmo_db.dtos.infos.CreditLineInfo;

import com.cmo.db.cmo_db.dtos.infos.OrganizationInfo;

import com.cmo.db.cmo_db.dtos.infos.OrganizationInfo;








public class OrganizationBaseDto {
	
	private Long _id;
	
	// Attributes
    private Boolean Active;
    private String ExternalID;
    private String FormalName;
    private Boolean Liable;
    private String SearchName;
    private String Type;
	
	// Relations Country
	private Long Country;
	
	// Relations Lessor
	private Long Lessor;
	
	// Relations LiableParent
	private Long LiableParent;
	
	// Relations CreditLine
	private List<Long> Organization_CreditLine = new ArrayList<>();
	
	// Relations Parent
	private Long Parent;
	
	// Relations UtlimateParent
	private Long UtlimateParent;
	
	
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public Boolean getActive() {
		return Active;
	}

	public void setActive(Boolean Active) {
		this.Active = Active;
	}
	public String getExternalID() {
		return ExternalID;
	}

	public void setExternalID(String ExternalID) {
		this.ExternalID = ExternalID;
	}
	public String getFormalName() {
		return FormalName;
	}

	public void setFormalName(String FormalName) {
		this.FormalName = FormalName;
	}
	public Boolean getLiable() {
		return Liable;
	}

	public void setLiable(Boolean Liable) {
		this.Liable = Liable;
	}
	public String getSearchName() {
		return SearchName;
	}

	public void setSearchName(String SearchName) {
		this.SearchName = SearchName;
	}
	public String getType() {
		return Type;
	}

	public void setType(String Type) {
		this.Type = Type;
	}
    
	public void setCountry(CountryInfo Country) {
		this.Country = Country.get_id();
	}

	public Long getCountry() {
		return Country;
	}
	
	public void setLessor(LessorInfo Lessor) {
		this.Lessor = Lessor.get_id();
	}

	public Long getLessor() {
		return Lessor;
	}
	
	public void setLiableParent(OrganizationInfo LiableParent) {
		this.LiableParent = LiableParent.get_id();
	}

	public Long getLiableParent() {
		return LiableParent;
	}
	
	// Relations CreditLine
	
	public List<Long> getOrganization_CreditLine() {
		return this.Organization_CreditLine;
	}

    public void setOrganization_CreditLine(List<CreditLineInfo> list) {
		this.Organization_CreditLine = list.stream()
				.map(el -> el.get_id())
				.collect(Collectors.toList());
	}

	
	public void setParent(OrganizationInfo Parent) {
		this.Parent = Parent.get_id();
	}

	public Long getParent() {
		return Parent;
	}
	
	public void setUtlimateParent(OrganizationInfo UtlimateParent) {
		this.UtlimateParent = UtlimateParent.get_id();
	}

	public Long getUtlimateParent() {
		return UtlimateParent;
	}
	

    
}