package com.cmo.db.cmo_db.dtos.infos.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE CreditLineInfoDto PLEASE EDIT ../CreditLineInfo.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the info of CreditLine object
 * 
 */

import java.util.Date;
import java.util.ArrayList;
import java.util.List;


public class CreditLineBaseInfo {
	
	private Long _id;
	// Attributes
    private Integer CreditLimit;
    private Date EndDate;
    private Integer GroupCreditLimit;
    private Date StartDate;
    private String Type;
	
	public Long get_id() {
		return _id;
	}

	public void set_id(Long id) {
		this._id = id;
	}
	
	public Integer getCreditLimit() {
		return CreditLimit;
	}

	public void setCreditLimit(Integer CreditLimit) {
		this.CreditLimit = CreditLimit;
	}
	public Date getEndDate() {
		return EndDate;
	}

	public void setEndDate(Date EndDate) {
		this.EndDate = EndDate;
	}
	public Integer getGroupCreditLimit() {
		return GroupCreditLimit;
	}

	public void setGroupCreditLimit(Integer GroupCreditLimit) {
		this.GroupCreditLimit = GroupCreditLimit;
	}
	public Date getStartDate() {
		return StartDate;
	}

	public void setStartDate(Date StartDate) {
		this.StartDate = StartDate;
	}
	public String getType() {
		return Type;
	}

	public void setType(String Type) {
		this.Type = Type;
	}
}